# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android app build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '11'
        distribution: adopt

    - name: "Build Android project"
      run: bash gradlew assembleDebug
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: app/build/outputs/apk/debug
